import { createContext, useContext, useState, useEffect } from 'react'

const LanguageContext = createContext()

// 1. Translation Dictionary (English and Gujarati)
export const translations = {
  en: {
    // Languages
    en: 'English',
    gu: 'ગુજરાતી',
    
    // Header Navigation Categories
    'Start Business': 'Start Business',
    'Registration & Licence': 'Registration & Licence',
    'Trademark & IPR': 'Trademark & IPR',
    'Tax & Compliances': 'Tax & Compliances',
    'Tax & Compliance': 'Tax & Compliance',
    'Other Services': 'Other Services',
    
    // Mega Menu Column Titles
    'POPULAR OPTIONS': 'POPULAR OPTIONS',
    'SPECIAL BUSINESS ENTITIES': 'SPECIAL BUSINESS ENTITIES',
    'CORE LICENSES': 'CORE LICENSES',
    'FOOD SAFETY & STANDARDS': 'FOOD SAFETY & STANDARDS',
    'BRAND PROTECTION': 'BRAND PROTECTION',
    'INTELLECTUAL PROPERTY': 'INTELLECTUAL PROPERTY',
    'GST & TAXATION': 'GST & TAXATION',
    'LABOUR & GENERAL FILINGS': 'LABOUR & GENERAL FILINGS',

    // Mega Menu / Footer Link Names
    'Private Limited Company': 'Private Limited Company',
    'Limited Liability Partnership': 'Limited Liability Partnership',
    'LLP Registration': 'LLP Registration',
    'One Person Company': 'One Person Company',
    'Sole Proprietorship': 'Sole Proprietorship',
    'Public Limited Company': 'Public Limited Company',
    'Section 8 Company': 'Section 8 Company',
    'Nidhi Company': 'Nidhi Company',
    'Import Export Code': 'Import Export Code',
    'Import Export Modification': 'Import Export Modification',
    'ISO Certificate': 'ISO Certificate',
    'ISO Certification': 'ISO Certification',
    'FSSAI Registration': 'FSSAI Registration',
    'FSSAI Renewal': 'FSSAI Renewal',
    'FSSAI License': 'FSSAI License',
    'Trademark Registration': 'Trademark Registration',
    'Trademark Renewal': 'Trademark Renewal',
    'Trademark Objection': 'Trademark Objection',
    'Copyright Registration': 'Copyright Registration',
    'GST Registration': 'GST Registration',
    'GST Return Filing': 'GST Return Filing',
    'Income Tax Return': 'Income Tax Return',
    'PF Registration': 'PF Registration',
    'ESIC Registration': 'ESIC Registration',
    'Consumer Complaint': 'Consumer Complaint',
    'RTI Filing': 'RTI Filing',
    
    // General / UI / Buttons
    Home: 'Home',
    'About Us': 'About Us',
    'Contact Us': 'Contact Us',
    Blogs: 'Blogs',
    'Get Started': 'Get Started',
    'View Details': 'View Details',
    'Register Now': 'Register Now',
    'Register Company Now': 'Register Company Now',
    'Register Proprietorship': 'Register Proprietorship',
    'First Name': 'First Name',
    'Last Name': 'Last Name',
    'Mobile Number': 'Mobile Number',
    'Email Address': 'Email Address',
    'Select State': 'Select State',
    'Choose State': '— Choose State —',
    'Select Plan': 'Select Plan',
    
    // Hero Section Copy
    heroLabel: "Authorized Aadhaar & Digital Service Hub",
    heroHeadingMain: "SHIVANI DIGITAL HUB",
    heroHeadingHighlight: "Aadhaar Center in Manjalpur, Vadodara",
    heroSub: "PRIVATE GOVERNMENT SERVICES: NEW AADHAR CARD (CORRECTION), Aadhaar Mobile Number Link, Aadhaar Address & Date of Birth Correction, NEW PAN CARD (CORRECTION), VOTER CARD (CORRECTION), ALL TYPES OF DIGITAL WORK, ITR FILING, RTO WORK, LOAN CONSULTANT, PF WITHDRAWAL, Pension Withdrawal, PF Death Claim, ESIC Cash Claim.",
    heroTalkBtn: "Talk to our Experts",
    heroExploreBtn: "Explore Services",
    heroBadge1: "10+ Years Professional Track Record",
    heroBadge2: "Government Recognized Firm",
    heroBadge3: "100% Satisfaction Guaranteed",
    heroBadge4: "Dedicated Case Managers",
    heroTrustText: "Trusted by 50,000+ businesses across India.",
    // Services Section
    servicesTitle: "Comprehensive Services",
    servicesSub: "Simplify your legal, tax, and registration compliance requirements with our expert solutions.",
    'All': 'All',
    'Company Incorporation': 'Company Incorporation',
    'GST Services': 'GST Services',
    'Trademark Services': 'Trademark Services',
    'FSSAI Food License': 'FSSAI Food License',
    'EPF Compliances': 'EPF Compliances',
    'Learn More': 'Learn More',
    'Register your dream company online with us and start your journey as an entrepreneur.': 'Register your dream company online with us and start your journey as an entrepreneur.',
    'Outsource your GST compliance to Shivani Digital Hub. Expert help in GST Registration and Return Filing.': 'Outsource your GST compliance to Shivani Digital Hub. Expert help in GST Registration and Return Filing.',
    'Protect your Brand Name, Logo and Slogan by doing trademark registration at nominal cost.': 'Protect your Brand Name, Logo and Slogan by doing trademark registration at nominal cost.',
    'Get Food License Certificate for your food business. Register for FSSAI today.': 'Get Food License Certificate for your food business. Register for FSSAI today.',
    'Apply for IEC Registration and start your import export business in 1 day.': 'Apply for IEC Registration and start your import export business in 1 day.',
    'Register your business as a sole proprietor and be your own boss from today.': 'Register your business as a sole proprietor and be your own boss from today.',
    'File Income Tax return online with us. Hassle free process to file ITR and get quick refunds.': 'File Income Tax return online with us. Hassle free process to file ITR and get quick refunds.',
    'Build brand authority and trust with ISO Certification for your business.': 'Build brand authority and trust with ISO Certification for your business.',
    'File your monthly or quarterly GST returns (GSTR-1, GSTR 3B) with our experts.': 'File your monthly or quarterly GST returns (GSTR-1, GSTR 3B) with our experts.',
    'Register your business under EPF act and get compliances done by our expert.': 'Register your business under EPF act and get compliances done by our expert.',
    'Submit your consumer complaint online. File your case in consumer court/forum.': 'Submit your consumer complaint online. File your case in consumer court/forum.',
    'File RTI online and get details from any government department in India.': 'File RTI online and get details from any government department in India.',
    
    // About Section
    aboutSubtitle: "Who We Are",
    aboutTitle: "Empowering Your Business with Legal & Financial Excellence",
    aboutDesc: "Shivani Digital Hub is India's leading corporate digital hub, transforming complex regulations into simple, accessible business pathways.",
    aboutIntroTitle: "LOOKING FOR RELIABLE LEGAL SERVICES ONLINE?",
    aboutIntroDesc: "Navigating Indian corporate law, taxation filings, and licenses can be daunting. We operate as your direct strategic partner, bringing world-class professional counseling straight to your screen.",
    aboutTabIdentity: "Our Identity",
    aboutTabAim: "Our Aim",
    aboutTabWhyUs: "Why Choose Us",
    aboutTab1Heading: "Advocates, CAs & CSs Under One Roof",
    aboutTab1Desc: "Shivani Digital Hub is registered and recognized by the Govt. of India. Our unified professional force comprises highly experienced Advocates, Chartered Accountants (CAs), and Company Secretaries (CSs) collaborating seamlessly to satisfy all your legal and financial compliance requirements in one cohesive experience.",
    aboutTab1Bullet1: "Govt. Certified & Recognized",
    aboutTab1Bullet2: "Unified Multi-Expert Team",
    aboutTab1Bullet3: "Complete End-to-End Filing",
    aboutTab1Bullet4: "100% Privacy & Data Security",
    aboutTab2Heading: "Removing Legal Complexity Completely",
    aboutTab2Desc: "Our aim is to provide absolute peace of mind by deeply understanding your business goals and solving tax or licensing problems effectively. We are committed to stripping away the confusing legal jargon, long procedural delays, and making your regulatory compliance incredibly smooth.",
    aboutTab2Bullet1: "Simplified Legal Frameworks",
    aboutTab2Bullet2: "Proactive Business Advisory",
    aboutTab2Bullet3: "Rapid Registration Service",
    aboutTab2Bullet4: "Hassle-Free Taxation Filing",
    aboutTab3Heading: "Your Success is Our Responsibility",
    aboutTab3Desc: "Over a decade of excellent service across India has taught us that trust is built on transparency. We stand by our promise of fixed upfront pricing, dedicated support representatives, prompt filing timelines, and a completely digital environment that saves your precious hours.",
    aboutTab3Bullet1: "10+ Years Trusted Track Record",
    aboutTab3Bullet2: "100% Upfront Clear Pricing",
    aboutTab3Bullet3: "Personalized Case Managers",
    aboutTab3Bullet4: "Continuous Compliance Tracking",
    aboutConsultBtn: "Get Free Consultation",
    aboutBadgeGovtLabel: "Govt. Recognized",
    aboutBadgeGovtDesc: "Ministry of MSME / India",
    aboutBadgeTrustLabel: "10+ Years Trust",
    
    // Why Choose Us Section
    whyUsSubtitle: "Why Choose Us",
    whyUsSectionTitle: "A Decade of Verified Trust & Excellence",
    whyUsSectionDesc: "We bridge the gap between complex legal regulatory compliance and your business success with transparent pricing, certified experts, and rapid processing.",
    'Recognized by Govt. of India': 'Recognized by Govt. of India',
    'Authorized digital corporate filing and compliance consulting hub registered under the Ministry of MSME.': 'Authorized digital corporate filing and compliance consulting hub registered under the Ministry of MSME.',
    '10+ Years Trusted Track Record': '10+ Years Trusted Track Record',
    'Over a decade of successful corporate registrations, tax filings, and strategic legal consultancies across India.': 'Over a decade of successful corporate registrations, tax filings, and strategic legal consultancies across India.',
    'ISO Certified Quality': 'ISO Certified Quality',
    'Operating under internationally recognized security and management standards for complete operational excellence.': 'Operating under internationally recognized security and management standards for complete operational excellence.',
    'Immediate Response & Filing': 'Immediate Response & Filing',
    'Same-day document validation and rapid electronic filing processes to get your approvals as fast as possible.': 'Same-day document validation and rapid electronic filing processes to get your approvals as fast as possible.',
    '50,000+ Happy Entrepreneurs': '50,000+ Happy Entrepreneurs',
    'Trusted strategic partner for thousands of startups, SME owners, self-employed creators, and corporations.': 'Trusted strategic partner for thousands of startups, SME owners, self-employed creators, and corporations.',
    'Best & Affordable Pricing': 'Best & Affordable Pricing',
    'Fixed, transparent, flat upfront rates with absolutely zero hidden professional fees or unexpected charges.': 'Fixed, transparent, flat upfront rates with absolutely zero hidden professional fees or unexpected charges.',
    'Expert Multi-Disciplinary Staff': 'Expert Multi-Disciplinary Staff',
    'Direct consultation desk with highly certified Advocates, Chartered Accountants (CAs), and Company Secretaries.': 'Direct consultation desk with highly certified Advocates, Chartered Accountants (CAs), and Company Secretaries.',
    '24/7 Dedicated Support': '24/7 Dedicated Support',
    'Continuous status updates and instant WhatsApp assistance with a personalized legal support manager.': 'Continuous status updates and instant WhatsApp assistance with a personalized legal support manager.',
    '100% Satisfaction Guarantee': '100% Satisfaction Guarantee',
    'Committed to ultimate compliance accuracy, clean error-free documentation, and maximum tax savings.': 'Committed to ultimate compliance accuracy, clean error-free documentation, and maximum tax savings.',
    
    // Contact Section
    contactBadge: "DON'T BE SHY",
    contactHeading: "Reach out",
    contactDescription: "Have questions or need legal assistance? Contact us today—our team is here to help. Whether by phone, email, or through our online form, we're ready to listen and provide the support you need.",
    'Name': 'Name',
    'Email': 'Email',
    'Phone Number': 'Phone Number',
    'Service Required': 'Service Required',
    'Message': 'Message',
    'Enter Name': 'Enter Name',
    'Enter Phone': 'Enter Phone',
    'Select a service': 'Select a service',
    'Enter Message...': 'Enter Message...',
    'Send Message': 'Send Message',
    'Processing...': 'Processing...',
    'Other': 'Other',
    'Please select a service': 'Please select a service',
    '✓ Opening WhatsApp to send your message...': '✓ Opening WhatsApp to send your message...',
    'Name is required': 'Name is required',
    'Phone is required': 'Phone is required',
    'Please enter a valid phone number': 'Please enter a valid phone number',
    'Please enter a valid email address': 'Please enter a valid email address',

    // Footer Section
    footerDesc: "Registered and recognised by the Govt of India. Providing expert legal, taxation and business services across India since 2013.",
    footerQuickLinks: "Quick Links",
    footerContactUs: "Contact Us",
    footerEmail: "Email:",
    footerPhone: "Phone:",
    footerAddress: "Address:",
    footerContactInfo: "Contact Information",
    footerAddressVal: "5th Avenue, GF-12, Alwa Naka, GIDC Road, Manjalapur, Vadodara - 390 011, Gujarat, India",
    footerLocation: "Google Map Location",
    footerRights: "Shivani Digital Hub. All rights reserved.",
    'Privacy Policy': 'Privacy Policy',
    'Terms of Service': 'Terms of Service',
    'File Your Complaint': 'File Your Complaint',
    'Register Copyright': 'Register Copyright',
    'Register & File EPF': 'Register & File EPF',
    'Register ESIC Now': 'Register ESIC Now',
    'Get Food License Today': 'Get Food License Today',
    'Renew FSSAI License Now': 'Renew FSSAI License Now',
    'Get Your IEC in 1 Day': 'Get Your IEC in 1 Day',
    'File Your ITR Now': 'File Your ITR Now',
    'Get ISO Certified Today': 'Get ISO Certified Today',
    'Register Your LLP': 'Register Your LLP',
    'Register Your Nidhi Company': 'Register Your Nidhi Company',
    'Register Company Now': 'Register Company Now',
    'First Step to Start Your Business': 'First Step to Start Your Business',
    'File Your RTI Online': 'File Your RTI Online',
    'Register Your Section 8 NGO': 'Register Your Section 8 NGO',
    'Register Proprietorship': 'Register Proprietorship',
    'Modify Your IEC Now': 'Modify Your IEC Now',
    'Respond to Objection Now': 'Respond to Objection Now',
    'Renew Your TM Now': 'Renew Your TM Now',
    'Protect Your Brand Name': 'Protect Your Brand Name',
    'GST Compliance Setup': 'GST Compliance Setup',
    'GST Return Setup': 'GST Return Setup',
    'Start Your OPC': 'Start Your OPC',
    'Search services...': 'Search services...',
    'No services found matching your search.': 'No services found matching your search.',
    'This will open WhatsApp with your message details pre-filled.': 'This will open WhatsApp with your message details pre-filled.',
    'Try searching for different keywords or select a different category.': 'Try searching for different keywords or select a different category.'
  },
  gu: {
    // Languages
    en: 'English',
    gu: 'ગુજરાતી',

    // Form Field Labels & Actions
    'Choose State': 'રાજ્ય પસંદ કરો',
    'Email Address': 'ઇમેઇલ સરનામું',
    'First Name': 'પ્રથમ નામ',
    'Get Started': 'શરૂ કરો',
    'Last Name': 'અટક',
    'Mobile Number': 'મોબાઈલ નંબર',
    'Register Company Now': 'કંપની રજીસ્ટર કરો',
    'Register Now': 'હમણાં નોંધણી કરો',
    'Register Proprietorship': 'પ્રોપ્રાઇટરશિપ રજીસ્ટર કરો',
    'Select Plan': 'પ્લાન પસંદ કરો',
    'Select State': 'રાજ્ય પસંદ કરો',
    'View Details': 'વિગતો જુઓ',

    // Hero Section Copy
    heroLabel: "Authorized Aadhaar & Digital Service Hub",
    heroHeadingMain: "SHIVANI DIGITAL HUB",
    heroHeadingHighlight: "Aadhaar Center in Manjalpur, Vadodara",
    heroSub: "PRIVATE GOVERNMENT SERVICES: NEW AADHAR CARD (CORRECTION), Aadhaar Mobile Number Link, Aadhaar Address & Date of Birth Correction, NEW PAN CARD (CORRECTION), VOTER CARD (CORRECTION), ALL TYPES OF DIGITAL WORK, ITR FILING, RTO WORK, LOAN CONSULTANT, PF WITHDRAWAL, Pension Withdrawal, PF Death Claim, ESIC Cash Claim.",
    heroTalkBtn: 'અમારા નિષ્ણાતો સાથે વાત કરો',
    heroExploreBtn: 'સેવાઓ શોધો',
    heroBadge1: '૧૦+ વર્ષનો વ્યાવસાયિક ટ્રેક રેકોર્ડ',
    heroBadge2: 'સરકાર માન્ય પેઢી',
    heroBadge3: '૧૦૦% સંતોષની ગેરંટી',
    heroBadge4: 'સમર્પિત કેસ મેનેજર્સ',
    heroTrustText: 'ભારતભરમાં ૫૦,૦૦૦+ વ્યવસાયો દ્વારા વિશ્વસનીય.',
    
    // Header Navigation Categories
    'Start Business': 'વ્યવસાય શરૂ કરો',
    'Registration & Licence': 'નોંધણી અને લાયસન્સ',
    'Trademark & IPR': 'ટ્રેડમાર્ક અને આઈપીઆર',
    'Tax & Compliances': 'ટેક્સ અને પાલન',
    'Tax & Compliance': 'ટેક્સ અને પાલન',
    'Other Services': 'અન્ય સેવાઓ',
    
    // Mega Menu Column Titles
    'POPULAR OPTIONS': 'લોકપ્રિય વિકલ્પો',
    'SPECIAL BUSINESS ENTITIES': 'ખાસ વ્યવસાયિક સંસ્થાઓ',
    'CORE LICENSES': 'મુખ્ય લાયસન્સ',
    'FOOD SAFETY & STANDARDS': 'ખાદ્ય સુરક્ષા અને ધોરણો',
    'BRAND PROTECTION': 'બ્રાન્ડ પ્રોટેક્શન',
    'INTELLECTUAL PROPERTY': 'બૌદ્ધિક સંપત્તિ',
    'GST & TAXATION': 'જીએસટી અને ટેક્સેશન',
    'LABOUR & GENERAL FILINGS': 'શ્રમ અને સામાન્ય ફાઇલિંગ',
    
    // Mega Menu / Footer Link Names
    'Private Limited Company': 'પ્રાઇવેટ લિમિટેડ કંપની',
    'Limited Liability Partnership': 'લિમિટેડ લાયબિલિટી પાર્ટનરશિપ',
    'LLP Registration': 'LLP નોંધણી',
    'One Person Company': 'વન પર્સન કંપની',
    'Sole Proprietorship': 'સોલ પ્રોપ્રાઇટરશિપ',
    'Public Limited Company': 'પબ્લિક લિમિટેડ કંપની',
    'Section 8 Company': 'સેક્શન ૮ કંપની',
    'Nidhi Company': 'નિધિ કંપની',
    'Import Export Code': 'આયાત નિકાસ કોડ (IEC)',
    'Import Export Modification': 'આયાત નિકાસ સુધારો',
    'ISO Certificate': 'ISO સર્ટિફિકેટ',
    'ISO Certification': 'ISO સર્ટિફિકેટ',
    'FSSAI Registration': 'FSSAI ફૂડ લાયસન્સ',
    'FSSAI Renewal': 'FSSAI રિન્યુઅલ',
    'FSSAI License': 'FSSAI ફૂડ લાયસન્સ',
    'Trademark Registration': 'ટ્રેડમાર્ક નોંધણી',
    'Trademark Renewal': 'ટ્રેડમાર્ક રિન્યુઅલ',
    'Trademark Objection': 'ટ્રેડમાર્ક વાંધો',
    'Copyright Registration': 'કોપીરાઇટ નોંધણી',
    'GST Registration': 'GST નોંધણી',
    'GST Return Filing': 'GST રિટર્ન ફાઇલિંગ',
    'Income Tax Return': 'ઇનકમ ટેક્સ રિટર્ન (ITR)',
    'PF Registration': 'PF નોંધણી (EPF)',
    'ESIC Registration': 'ESIC નોંધણી',
    'Consumer Complaint': 'ગ્રાહક ફરિયાદ',
    'RTI Filing': 'RTI ફાઇલિંગ',
    
    // General / UI / Buttons
    Home: 'હોમ',
    'About Us': 'અમારા વિશે',
    'Contact Us': 'અમારો સંપર્ક કરો',
    Blogs: 'બ્લોગ્સ',
     // Services Section
    servicesTitle: "અમારી તમામ સેવાઓ",
    servicesSub: "અમારા નિષ્ણાત ઉકેલો સાથે તમારી કાનૂની, ટેક્સ અને નોંધણી પાલનની જરૂરિયાતોને સરળ બનાવો.",
    'All': 'બધા',
    'Company Incorporation': 'કંપની નોંધણી',
    'GST Services': 'GST સેવાઓ',
    'Trademark Services': 'ટ્રેડમાર્ક સેવાઓ',
    'FSSAI Food License': 'FSSAI ફૂડ લાયસન્સ',
    'EPF Compliances': 'EPF પાલન',
    'Learn More': 'વધુ જાણો',
    'Register your dream company online with us and start your journey as an entrepreneur.': 'અમારી સાથે ઓનલાઇન તમારી સ્વપ્નની કંપની રજીસ્ટર કરો અને એક ઉદ્યોગસાહસિક તરીકે તમારી મુસાફરી શરૂ કરો.',
    'Outsource your GST compliance to Shivani Digital Hub. Expert help in GST Registration and Return Filing.': 'તમારા GST પાલનનું કામ શિવાની ડિજિટલ હબને સોંપો. GST નોંધણી અને રિટર્ન ફાઇલિંગમાં નિષ્ણાત મદદ.',
    'Protect your Brand Name, Logo and Slogan by doing trademark registration at nominal cost.': 'નામ માત્રના ખર્ચે ટ્રેડમાર્ક નોંધણી કરાવીને તમારા બ્રાન્ડનું નામ, લોગો અને સ્લોગન સુરક્ષિત કરો.',
    'Get Food License Certificate for your food business. Register for FSSAI today.': 'તમારા ખાદ્ય વ્યવસાય માટે ફૂડ લાયસન્સ પ્રમાણપત્ર મેળવો. આજે જ FSSAI માટે નોંધણી કરો.',
    'Apply for IEC Registration and start your import export business in 1 day.': 'IEC નોંધણી માટે અરજી કરો અને ૧ દિવસમાં તમારો આયાત નિકાસ વ્યવસાય શરૂ કરો.',
    'Register your business as a sole proprietor and be your own boss from today.': 'તમારા વ્યવસાયને સોલ પ્રોપ્રાઇટર તરીકે રજીસ્ટર કરો અને આજથી જ તમારા પોતાના માલિક બનો.',
    'File Income Tax return online with us. Hassle free process to file ITR and get quick refunds.': 'અમારી સાથે ઓનલાઇન ઇનકમ ટેક્સ રિટર્ન ફાઇલ કરો. ITR ફાઇલ કરવાની અને ઝડપી રિફંડ મેળવવાની સરળ પ્રક્રિયા.',
    'Build brand authority and trust with ISO Certification for your business.': 'તમારા વ્યવસાય માટે ISO પ્રમાણપત્ર મેળવીને બ્રાન્ડ સત્તા અને વિશ્વાસ બનાવો.',
    'File your monthly or quarterly GST returns (GSTR-1, GSTR 3B) with our experts.': 'અમારા નિષ્ણાતો સાથે તમારા માસિક અથવા ત્રિમાસિક GST રિટર્ન (GSTR-1, GSTR 3B) ફાઇલ કરો.',
    'Register your business under EPF act and get compliances done by our expert.': 'EPF એક્ટ હેઠળ તમારા વ્યવસાયની નોંધણી કરો અને અમારા નિષ્ણાત દ્વારા પાલનની કામગીરી કરાવો.',
    'Submit your consumer complaint online. File your case in consumer court/forum.': 'તમારી ગ્રાહક ફરિયાદ ઓનલાઇન સબમિટ કરો. ગ્રાહક અદાલત/ફોરમમાં તમારો કેસ ફાઇલ કરો.',
    'File RTI online and get details from any government department in India.': 'ઓનલાઇન RTI ફાઇલ કરો અને ભારતના કોઈપણ સરકારી વિભાગમાંથી વિગતો મેળવો.',

    // About Section
    aboutSubtitle: "અમારા વિશે",
    aboutTitle: "કાનૂની અને નાણાકીય શ્રેષ્ઠતા સાથે તમારા વ્યવસાયને સશક્ત બનાવવો",
    aboutDesc: "શિવાની ડિજિટલ હબ એ ભારતનું અગ્રણી કોર્પોરેટ ડિજિટલ હબ છે, જે જટિલ નિયમોને સરળ, સુલભ વ્યવસાયિક માર્ગોમાં ફેરવે છે.",
    aboutIntroTitle: "ઓનલાઇન વિશ્વસનીય કાનૂની સેવાઓ શોધી રહ્યા છો?",
    aboutIntroDesc: "ભારતીય કોર્પોરેટ કાયદા, ટેક્સ ફાઇલિંગ અને લાયસન્સની પ્રક્રિયા જટિલ હોઈ શકે છે. અમે તમારા સીધા વ્યૂહાત્મક ભાગીદાર તરીકે કામ કરીએ છીએ અને વિશ્વ-સ્તરિય વ્યાવસાયિક પરામર્શ સીધા તમારી સ્ક્રીન પર લાવીએ છીએ.",
    aboutTabIdentity: "અમારી ઓળખ",
    aboutTabAim: "અમારો હેતુ",
    aboutTabWhyUs: "શા માટે અમે",
    aboutTab1Heading: "એક જ છત નીચે વકીલો, CA અને CS",
    aboutTab1Desc: "શિવાની ડિજિટલ હબ ભારત સરકાર દ્વારા નોંધાયેલ અને માન્યતા પ્રાપ્ત છે. અમારું સંયુક્ત વ્યાવસાયિક જૂથ અત્યંત અનુભવી વકીલો, ચાર્ટર્ડ એકાઉન્ટન્ટ્સ (CAs) અને કંપની સેક્રેટરીઓ (CSs) નું બનેલું છે, જે તમારી બધી કાનૂની અને નાણાકીય પાલનની જરૂરિયાતોને એક જ પ્લેટફોર્મ પર પૂરી કરવા માટે સાથે મળીને કામ કરે છે.",
    aboutTab1Bullet1: "સરકાર પ્રમાણિત અને માન્ય",
    aboutTab1Bullet2: "સંયુક્ત બહુ-નિષ્ણાત ટીમ",
    aboutTab1Bullet3: "સંપૂર્ણ એન્ડ-ટુ-એન્ડ ફાઇલિંગ",
    aboutTab1Bullet4: "૧૦૦% ગોપનીયતા અને ડેટા સુરક્ષા",
    aboutTab2Heading: "કાનૂની જટિલતાને સંપૂર્ણપણે દૂર કરવી",
    aboutTab2Desc: "અમારો હેતુ તમારા વ્યવસાયિક લક્ષ્યોને ઊંડાણપૂર્વક સમજીને અને ટેક્સ અથવા લાયસન્સિંગ સમસ્યાઓનો અસરકારક રીતે ઉકેલ લાવીને તમને સંપૂર્ણ મનની શાંતિ પ્રદાન કરવાનો છે. અમે કાનૂની પરિભાષાઓ અને લાંબા વિલંબને દૂર કરીને તમારા નિયમનકારી પાલનને અત્યંત સરળ બનાવવા માટે પ્રતિબદ્ધ છીએ.",
    aboutTab2Bullet1: "સરળ કાનૂની માળખું",
    aboutTab2Bullet2: "સક્રિય વ્યવસાયિક સલાહ",
    aboutTab2Bullet3: "ઝડપી નોંધણી સેવા",
    aboutTab2Bullet4: "સરળ ટેક્સ ફાઇલિંગ",
    aboutTab3Heading: "તમારી સફળતા એ અમારી જવાબદારી છે",
    aboutTab3Desc: "સમગ્ર ભારતમાં એક દાયકાથી વધુની ઉત્કૃષ્ટ સેવાએ અમને શીખવ્યું છે કે વિશ્વાસ પારદર્શિતા પર બને છે. અમે અમારી નિશ્ચિત અગાઉની કિંમતો, સમર્પિત સપોર્ટ પ્રતિનિધિઓ, પ્રોમ્પ્ટ ફાઇલિંગ સમયરેખા અને સંપૂર્ણપણે ડિજિટલ વાતાવરણના વચન સાથે ઊભા છીએ જે તમારા મૂલ્યવાન કલાકો બચાવે છે.",
    aboutTab3Bullet1: "૧૦+ વર્ષનો વિશ્વસનીય ટ્રેક રેકોર્ડ",
    aboutTab3Bullet2: "૧૦૦% અગાઉથી સ્પષ્ટ કિંમતો",
    aboutTab3Bullet3: "વ્યક્તિગત કેસ મેનેજર્સ",
    aboutTab3Bullet4: "સતત પાલન ટ્રેકિંગ",
    aboutConsultBtn: "મફત પરામર્શ મેળવો",
    aboutBadgeGovtLabel: "સરકાર માન્ય",
    aboutBadgeGovtDesc: "MSME મંત્રાલય / ભારત",
    aboutBadgeTrustLabel: "૧૦+ વર્ષનો વિશ્વાસ",
    
    // Why Choose Us Section
    whyUsSubtitle: "શા માટે અમને પસંદ કરો",
    whyUsSectionTitle: "ચકાસાયેલ વિશ્વાસ અને શ્રેષ્ઠતાનો એક દાયકો",
    whyUsSectionDesc: "અમે પારદર્શક કિંમતો, પ્રમાણિત નિષ્ણાતો અને ઝડપી પ્રક્રિયા દ્વારા જટિલ કાનૂની નિયમનકારી પાલન અને તમારા વ્યવસાયની સફળતા વચ્ચેના અંતરને દૂર કરીએ છીએ.",
    'Recognized by Govt. of India': 'ભારત સરકાર દ્વારા માન્યતા પ્રાપ્ત',
    'Authorized digital corporate filing and compliance consulting hub registered under the Ministry of MSME.': 'MSME મંત્રાલય હેઠળ નોંધાયેલ સત્તાવાર ડિજિટલ કોર્પોરેટ ફાઇલિંગ અને પાલન કન્સલ્ટિંગ હબ.',
    '10+ Years Trusted Track Record': '૧૦+ વર્ષનો વિશ્વસનીય ટ્રેક રેકોર્ડ',
    'Over a decade of successful corporate registrations, tax filings, and strategic legal consultancies across India.': 'સમગ્ર ભારતમાં સફળ કોર્પોરેટ નોંધણીઓ, ટેક્સ ફાઇલિંગ અને વ્યૂહાત્મક કાનૂની પરામર્શનો એક દાયકાથી વધુ સમય.',
    'ISO Certified Quality': 'ISO પ્રમાણિત ગુણવત્તા',
    'Operating under internationally recognized security and management standards for complete operational excellence.': 'સંપૂર્ણ ઓપરેશનલ શ્રેષ્ઠતા માટે આંતરરાષ્ટ્રીય સ્તરે માન્ય સુરક્ષા અને વ્યવસ્થાપન ધોરણો હેઠળ કાર્યરત.',
    'Immediate Response & Filing': 'ઝડપી પ્રતિભાવ અને ફાઇલિંગ',
    'Same-day document validation and rapid electronic filing processes to get your approvals as fast as possible.': 'તમારી મંજૂરીઓ શક્ય તેટલી ઝડપથી મેળવવા માટે તે જ દિવસે દસ્તાવેજ ચકાસણી અને ઝડપી ઇલેક્ટ્રોનિક ફાઇલિંગ પ્રક્રિયાઓ.',
    '50,000+ Happy Entrepreneurs': '૫૦,૦૦૦+ ખુશ ઉદ્યોગસાહસિકો',
    'Trusted strategic partner for thousands of startups, SME owners, self-employed creators, and corporations.': 'હજારો સ્ટાર્ટઅપ્સ, SME માલિકો, સ્વ-રોજગાર ધરાવતા સર્જકો અને કોર્પોરેશનો માટે વિશ્વસનીય વ્યૂહાત્મક ભાગીદાર.',
    'Best & Affordable Pricing': 'શ્રેષ્ઠ અને સસ્તી કિંમતો',
    'Fixed, transparent, flat upfront rates with absolutely zero hidden professional fees or unexpected charges.': 'કોઈપણ છુપી વ્યવસાયિક ફી અથવા અણધાર્યા ચાર્જ વિના નિશ્ચિત, પારદર્શક, ફ્લેટ અપફ્રન્ટ દરો.',
    'Expert Multi-Disciplinary Staff': 'નિષ્ણાત બહુ-વિધિ સ્ટાફ',
    'Direct consultation desk with highly certified Advocates, Chartered Accountants (CAs), and Company Secretaries.': 'ઉચ્ચ પ્રમાણિત વકીલો, ચાર્ટર્ડ એકાઉન્ટન્ટ્સ (CAs) અને કંપની સેક્રેટરીઓ સાથે સીધો પરામર્શ ડેસ્ક.',
    '24/7 Dedicated Support': '૨૪/૭ સમર્પિત સપોર્ટ',
    'Continuous status updates and instant WhatsApp assistance with a personalized legal support manager.': 'વૈયક્તિકૃત કાનૂની સપોર્ટ મેનેજર સાથે સતત સ્ટેટસ અપડેટ્સ અને ત્વરિત વ્હોટ્સએપ સહાય.',
    '100% Satisfaction Guarantee': '૧૦૦% સંતોષની ગેરંટી',
    'Committed to ultimate compliance accuracy, clean error-free documentation, and maximum tax savings.': 'અંતિમ પાલનની ચોકસાઈ, સ્વચ્છ ભૂલ-મુક્ત દસ્તાવેજીકરણ અને મહત્તમ કર બચત માટે પ્રતિબદ્ધ.',
    
    // Contact Section
    contactBadge: "શરમાશો નહીં",
    contactHeading: "સંપર્ક કરો",
    contactDescription: "પ્રશ્નો છે કે કાનૂની સહાયની જરૂર છે? આજે જ અમારો સંપર્ક કરો—અમારી ટીમ મદદ માટે અહીં છે. પછી તે ફોન, ઇમેઇલ અથવા અમારા ઓનલાઇન ફોર્મ દ્વારા હોય, અમે સાંભળવા અને તમને જોઈતો સપોર્ટ આપવા તૈયાર છીએ.",
    'Name': 'નામ',
    'Email': 'ઇમેઇલ',
    'Phone Number': 'મોબાઇલ નંબર',
    'Service Required': 'જરૂરી સેવા',
    'Message': 'સંદેશો',
    'Enter Name': 'નામ દાખલ કરો',
    'Enter Phone': 'મોબાઇલ નંબર દાખલ કરો',
    'Select a service': 'સેવા પસંદ કરો',
    'Enter Message...': 'સંદેશો દાખલ કરો...',
    'Send Message': 'સંદેશો મોકલો',
    'Processing...': 'પ્રક્રિયા ચાલુ છે...',
    'Other': 'અન્ય',
    'Please select a service': 'કૃપા કરીને સેવા પસંદ કરો',
    '✓ Opening WhatsApp to send your message...': '✓ તમારો સંદેશ મોકલવા માટે WhatsApp ખોલી રહ્યા છીએ...',
    'Name is required': 'નામ જરૂરી છે',
    'Phone is required': 'મોબાઇલ નંબર જરૂરી છે',
    'Please enter a valid phone number': 'કૃપા કરીને માન્ય મોબાઇલ નંબર દાખલ કરો',
    'Please enter a valid email address': 'કૃપા કરીને માન્ય ઇમેઇલ સરનામું દાખલ કરો',

    // Footer Section
    footerDesc: "ભારત સરકાર દ્વારા નોંધાયેલ અને માન્યતા પ્રાપ્ત. ૨૦૧૩ થી સમગ્ર ભારતમાં નિષ્ણાત કાનૂની, કરવેરા અને વ્યવસાયિક સેવાઓ પ્રદાન કરીએ છીએ.",
    footerQuickLinks: "ઝડપી લિંક્સ",
    footerContactUs: "અમારો સંપર્ક કરો",
    footerEmail: "ઇમેઇલ:",
    footerPhone: "ફોન:",
    footerAddress: "સરનામું:",
    footerContactInfo: "સંપર્ક માહિતી",
    footerAddressVal: "૫ મી એવન્યુ, GF-12, અલવા નાકા, GIDC રોડ, માંજલપુર, વડોદરા - ૩૯૦ ૦૧૧, ગુજરાત, ભારત",
    footerLocation: "ગુગલ મેપ લોકેશન",
    footerRights: "શિવાની ડિજિટલ હબ. બધા હકો સુરક્ષિત.",
    'Privacy Policy': 'પ્રાઇવસી પોલિસી',
    'Terms of Service': 'સેવાની શરતો',
    aboutIdentityContent: "શિવાની ડિજિટલ હબ એ ટેકનોલોજી સંચાલિત પ્લેટફોર્મ છે જે ભારતમાં કાનૂની સેવાઓ પ્રદાન કરે છે. અમે સ્ટાર્ટઅપ્સ અને સ્થાપિત વ્યવસાયોને તેમની કાનૂની પાલનની જરૂરિયાતો સરળતાથી ઓનલાઇન સંચાલિત કરવામાં મદદ કરવા માટે સમર્પિત છીએ.",
    aboutAimContent: "અમારો હેતુ ભારતમાં દરેક ઉદ્યોગસાહસિક અને વ્યવસાય માલિક માટે કાનૂની અને પાલન સેવાઓ સરળ, સસ્તી અને ઝડપી બનાવવાનો છે, જેથી તેઓ સંપૂર્ણપણે વિકાસ પર ધ્યાન કેન્દ્રિત કરી શકે.",
    aboutWhyUsContent: "કાનૂની નિષ્ણાતો, CA, CS અને ટેક્નોલોજીની સમર્પિત ટીમ સાથે, અમે તમારા બધા કોર્પોરેટ ફાઇલિંગ માટે સચોટ પ્રક્રિયા, પારદર્શક કિંમતો અને ૧૦૦% ડેટા સુરક્ષાની ખાતરી આપીએ છીએ.",
    
    // Why Choose Us Section
    whyUsTitle: "શા માટે શિવાની ડિજિટલ હબ પસંદ કરવું?",
    whyUsCard1Title: "૧૦૦% પેપરલેસ સેટઅપ",
    whyUsCard1Desc: "દસ્તાવેજો સુરક્ષિત રીતે ઓનલાઇન અપલોડ કરો. અમારા ડિજિટલ પ્રોસેસિંગ સાધનો ભૌતિક કાગળકામને સંપૂર્ણપણે દૂર કરે છે.",
    whyUsCard2Title: "સમર્પિત CA/CS નિષ્ણાતો",
    whyUsCard2Desc: "દરેક તબક્કે પ્રમાણિત ચાર્ટર્ડ એકાઉન્ટન્ટ્સ અને કંપની સેક્રેટરીઓ દ્વારા તમારા ફાઇલિંગની સમીક્ષા કરાવો.",
    whyUsCard3Title: "પારદર્શક નિશ્ચિત કિંમતો",
    whyUsCard3Desc: "કોઈ છુપા ચાર્જ અથવા અણધાર્યા ફી નથી. અમારા ફ્લેટ-ફી પ્રાઇસીંગ પેકેજો પર તમે જે જુઓ છો તે જ ચૂકવો.",
    whyUsCard4Title: "સુપર ફાસ્ટ ડિલિવરી",
    whyUsCard4Desc: "અમે તમારા સમયની કદર કરીએ છીએ. વચન આપેલ સમયરેખાની અંદર પ્રમાણપત્રો અને ટેક્સ નોંધણીઓ મેળવો.",
    
    // Contact Section
    contactTitle: "અમારા કાનૂની નિષ્ણાતો સાથે જોડાઓ",
    contactSub: "નીચેનું ફોર્મ ભરો. અમારી ટીમ ૧૫ મિનિટમાં વ્હોટ્સએપ અથવા ઇમેઇલ દ્વારા તમારો સંપર્ક કરશે.",
    
    // Subpage form headings & Additional UI translations
    'File Your Complaint': 'તમારી ફરિયાદ નોંધાવો',
    'Register Copyright': 'કોપીરાઇટ નોંધણી કરો',
    'Register & File EPF': 'EPF નોંધણી અને ફાઇલિંગ',
    'Register ESIC Now': 'હમણાં ESIC નોંધણી કરો',
    'Get Food License Today': 'આજે જ ફૂડ લાયસન્સ મેળવો',
    'Renew FSSAI License Now': 'હમણાં FSSAI લાયસન્સ રિન્યૂ કરો',
    'Get Your IEC in 1 Day': '૧ દિવસમાં તમારો IEC મેળવો',
    'File Your ITR Now': 'હમણાં તમારો ITR ફાઇલ કરો',
    'Get ISO Certified Today': 'આજે જ ISO પ્રમાણિત મેળવો',
    'Register Your LLP': 'તમારા LLP ની નોંધણી કરો',
    'Register Your Nidhi Company': 'તમારી નિધિ કંપની રજીસ્ટર કરો',
    'Register Company Now': 'કંપની રજીસ્ટર કરો',
    'First Step to Start Your Business': 'તમારો વ્યવસાય શરૂ કરવાનું પ્રથમ પગલું',
    'File Your RTI Online': 'ઓનલાઇન RTI ફાઇલ કરો',
    'Register Your Section 8 NGO': 'તમારા સેક્શન ૮ NGO ની નોંધણી કરો',
    'Register Proprietorship': 'પ્રોપ્રાઇટરશિપ રજીસ્ટર કરો',
    'Modify Your IEC Now': 'હમણાં તમારો IEC સુધારો',
    'Respond to Objection Now': 'વાંધાનો જવાબ હમણાં આપો',
    'Renew Your TM Now': 'હમણાં તમારો TM રિન્યૂ કરો',
    'Protect Your Brand Name': 'તમારા બ્રાન્ડનું નામ સુરક્ષિત કરો',
    'GST Compliance Setup': 'GST પાલન સેટઅપ',
    'GST Return Setup': 'GST રિટર્ન સેટઅપ',
    'Start Your OPC': 'તમારો OPC શરૂ કરો',
    'Search services...': 'સેવાઓ શોધો...',
    'No services found matching your search.': 'તમારી શોધ સાથે મેળ ખાતી કોઈ સેવાઓ મળી નથી.',
    'This will open WhatsApp with your message details pre-filled.': 'આ તમારા સંદેશાની વિગતો સાથે વોટ્સએપ ઓપન કરશે.',
    'Try searching for different keywords or select a different category.': 'બીજા કીવર્ડ્સ સાથે શોધવાનો પ્રયાસ કરો અથવા અન્ય શ્રેણી પસંદ કરો.'
  }
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem('siteLanguage') || 'en'
  })

  const setLanguage = (lang) => {
    localStorage.setItem('siteLanguage', lang)
    setLanguageState(lang)
    document.documentElement.lang = lang
  }

  useEffect(() => {
    document.documentElement.lang = language
  }, [language])

  const t = (key) => {
    if (!key) return ''
    return translations[language]?.[key] || translations.en?.[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}
