export { default as About } from './About'
export { default as Blog } from './Blog'
export { default as Contact } from './Contact'
export { default as FloatingButtons } from './FloatingButtons'
export { default as Footer } from './Footer'
export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as LiveChat } from './LiveChat'
export { default as Services } from './Services'
export { default as WhyUs } from './WhyUs'
export { default as LeadForm } from './LeadForm'
export { default as FaqSection } from './FaqSection'

