import ServicePageLayout from '../layouts/ServicePageLayout'
import { useLanguage } from '../context/LanguageContext'

const advantages = [
  { icon: 'fa-clock', title: 'Avoid Late Fees & Interest', desc: 'Ensure timely filings to completely eliminate daily late fees and interest liabilities under GST laws.' },
  { icon: 'fa-coins', title: 'Maximize Input Tax Credit', desc: 'Save massive amounts by continuously reconciling purchase bills with GSTR-2B to extract every rupee of credit.' },
  { icon: 'fa-shield-alt', title: 'Zero Objections & Audits', desc: 'Keep your books in perfect alignment with government portals, eliminating the risk of tax notices.' },
  { icon: 'fa-chart-bar', title: 'Better Compliance Rating', desc: 'Maintain an excellent GST compliance profile, making it easier to secure loans and big corporate tenders.' },
]

const documents = [
  { icon: 'fa-file-invoice', title: 'Sales Invoices', desc: 'Invoices or billing records of all sales and exports made during the filing period' },
  { icon: 'fa-file-invoice-dollar', title: 'Purchase Invoices', desc: 'Invoices of all business purchases, capital goods, and services to claim Input Tax Credit' },
  { icon: 'fa-id-card', title: 'GSTIN Certificate', desc: 'Copy of your official GST registration certificate showing the active tax number' },
  { icon: 'fa-university', title: 'Bank Statements', desc: 'Active business bank account statements for the filing period transaction checks' },
  { icon: 'fa-truck', title: 'E-Way Bill Details', desc: 'Details of all generated E-Way bills for transportation of goods (if applicable)' },
  { icon: 'fa-history', title: 'Previous Return Copies', desc: 'Copies of the filed GST returns of the previous filing period (if any)' },
]

const nameRules = [
  { icon: 'fa-calendar-check', title: 'Filing Frequencies', desc: 'Businesses with turnover < ₹5 Crores can opt for QRMP quarterly return filing.' },
  { icon: 'fa-clipboard-check', title: 'Strict ITC Reconciliation', desc: 'ITC can only be claimed if your suppliers upload purchase bills in their GSTR-1, matching your GSTR-2B.' },
  { icon: 'fa-times-circle', title: 'Mandatory Nil Filing', desc: 'GST returns must be filed even if there are zero transactions in a month to avoid deactivation.' }
]

const faqsList = [
  { q: 'What is GST Return Filing?', a: 'GST return filing is a mandatory tax compliance process under which a registered taxpayer files a digital declaration of outward supplies (sales), inward supplies (purchases), taxes collected on sales, and taxes paid on purchases.' },
  { q: 'What are GSTR-1 and GSTR-3B?', a: 'GSTR-1 is a statement where you upload all details of your sales invoices. GSTR-3B is a monthly summary return where you calculate final tax liability, claim eligible Input Tax Credit, and pay the net taxes due.' },
  { q: 'Is it mandatory to file returns if there was no business?', a: 'Yes, filing is absolutely mandatory. If your business had zero transactions during a filing period, you must file a "NIL Return" before the due date to avoid daily late fees.' },
  { q: 'What is GSTR-2B and why is it important?', a: 'GSTR-2B is an auto-drafted, static Input Tax Credit (ITC) statement generated by the GST portal. It shows the eligible credit you can claim based on the sales invoices uploaded by your suppliers. You cannot claim more ITC than what appears in your GSTR-2B.' },
  { q: 'What are the penalties for late filing of GST returns?', a: 'Delaying return filings attracts a daily late fee of ₹50 per day (₹20 per day for NIL returns) up to a maximum cap, plus an interest rate of 18% per annum on the unpaid tax liability.' }
]

export default function GstReturnFiling() {
  const { t } = useLanguage()

  const processSteps = [
  {
    "badge": "?",
    "icon": null,
    "title": "1. Upload Monthly Sales/Purchases",
    "bullets": [
      "Select your preferred return filing package",
      "Upload your sales invoices and purchase bills",
      "Complete secure payment"
    ]
  },
  {
    "badge": null,
    "icon": "fa-user",
    "title": "2. Reconciliation & Draft",
    "bullets": [
      "We reconcile your bills with GSTR-2B portal data",
      "We maximize your eligible Input Tax Credit (ITC)",
      "We prepare GSTR-1 and GSTR-3B drafts and send them for your approval"
    ]
  },
  {
    "badge": null,
    "icon": "fa-check",
    "title": "3. Filing & ARN generation",
    "bullets": [
      "We file the returns on the official GST portal",
      "We generate the ARN and send the final PDF acknowledgments to you"
    ]
  }
]

  const timelineSteps = [
  {
    "badge": null,
    "icon": "fa-clipboard-check",
    "title": "Days 1 - 5",
    "bullets": [
      "Gathering invoices, purchase bills, and account data",
      "Reconciling sales details with your bank statements",
      "Downloading GSTR-2B data for Input Tax Credit matching"
    ]
  },
  {
    "badge": "GSTR-1",
    "icon": null,
    "title": "Days 6 - 10",
    "bullets": [
      "Uploading b2b and b2c sales details in GSTR-1",
      "Filing GSTR-1 before the 11th of the succeeding month"
    ]
  },
  {
    "badge": null,
    "icon": "fa-calendar-alt",
    "title": "Days 11 - 20",
    "bullets": [
      "Computing net tax liability and checking available ITC offsets",
      "Preparing and filing GSTR-3B before the 20th of the month",
      "Delivering final filing acknowledgments directly to you"
    ]
  }
]

  return (
    <ServicePageLayout
      title={t("Online GST Return Filing Services")}
      serviceName="GST Return Filing"
      heroBg={"/hero-gst-return.webp"}
      heroDesc={[
        t("File your monthly or quarterly GST returns (GSTR-1, GSTR-3B, GSTR-9) with our experts. Get completely reconciled accounts, maximized Input Tax Credit, and zero late fees with Shivani Digital Hub."),
        t("Outsource your complex GST tax filings to our professional accountants. We reconcile your sales and purchase invoices (GSTR-2B matching) to maximize Input Tax Credit (ITC) and submit GSTR-1 & GSTR-3B filings accurately.")
      ]}
      overviewBadge={t("Introduction")}
      overviewTitle={t("Monthly & Quarterly GST Return Filing Services")}
      overviewParagraphs={[
        t("GST return filing is a compulsory statutory compliance requirement for all businesses holding a valid 15-digit GSTIN (Goods and Services Tax Identification Number) in India. Filing returns serves as a formal declaration of your sales, purchases, taxes collected on sales, and taxes paid on purchases to the government authorities."),
        t("Our professional CA Assisted GST compliance services eliminate the stress of manual calculation. We gather your monthly or quarterly invoices, reconcile your purchases with the portal's GSTR-2B data to maximize Input Tax Credit, prepare GSTR-1 (sales details) and GSTR-3B (tax self-declaration), file them securely on the government portal before the due dates, and ensure you remain fully compliant.")
      ]}
      benefitsBadge={t("Benefits")}
      benefitsTitle={t("Why Reconcile and File Your GST Returns on Time?")}
      benefits={advantages}
      documentsBadge={t("Documents Checklist")}
      documentsTitle={t("Invoices & Papers Required for GST return filing")}
      documents={documents}
      guidelinesBadge={t("Rules")}
      guidelinesTitle={t("Important GST Compliance & Credit Rules")}
      guidelines={nameRules}
      processSubtitle={t("GET CERTIFIED WITH CSC SHIVANI")}
      processTitle={t("GST Return Filing in Three Easy Steps!")}
      processSteps={processSteps}
      timelineSubtitle={t("PROCESSING TIMELINE")}
      timelineTitle={t("Seamless Registration Flow")}
      timelineSteps={timelineSteps}
      faqs={faqsList}
      
    />
  )
}
